baseURL = 'https://atablefortwo.github.io/'
languageCode = 'pt-br'
title = 'A Table For Two Blog'
theme = 'gokarna'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  pre = "<span data-feather='home'></span>" 

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
  pre = "<span data-feather='book'></span>" 

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
  pre = "<span data-feather='tag'></span>" 

[params]
  fontSize = "1.0rem"
  customHeadHTML = '''
  <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Play:wght@400;700&family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
  <style>
    body, .content { 
      font-family: "Reddit Mono", sans-serif; 
    }

    hr {
      margin-top: 0.5rem;
      margin-bottom: 0.5rem;
      width: 100%;
    }
  </style>
  '''