baseURL = 'https://atablefortwo.github.io/'
languageCode = 'pt-br'
title = 'A Table For Two Blog'
theme = 'gokarna'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  pre = "<span data-feather='home'></span>" 

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
  pre = "<span data-feather='book'></span>" 

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
  pre = "<span data-feather='tag'></span>" 
